name: Build Docker image from fork

on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone forked repo
        run: |
          git clone https://github.com/openrpa-bot/openalgo.git source
          cd source
          git log -1 --oneline

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./source
          push: true
          tags: |
            rahulnigamfzd/openalgo:latest
            rahulnigamfzd/openalgo:${{ github.event.client_payload.commit || github.run_number }}
